# syntax=docker/dockerfile:1
FROM public.ecr.aws/nullplatform/scopes/worker-bridge:1.1.1

RUN apk add --no-cache aws-cli gomplate bzip2

ARG TOFU_VERSION=1.12.6
ARG TARGETARCH
RUN curl -fsSL "https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_${TARGETARCH}.tar.gz" \
      | tar -xz -C /usr/local/bin tofu \
    && tofu version

ARG SQLCMD_VERSION=1.10.0
RUN curl -fsSL "https://github.com/microsoft/go-sqlcmd/releases/download/v${SQLCMD_VERSION}/sqlcmd-linux-${TARGETARCH}.tar.bz2" \
      | tar -xj -C /usr/local/bin sqlcmd \
    && chmod +x /usr/local/bin/sqlcmd \
    && sqlcmd --version

COPY . /app/pkg
ENV NP_PACKAGE_NAME=rds-sqlserver-db \
    NP_SERVICE_PATH=/app/pkg/rds-sqlserver-db \
    NP_SCOPE_ENTRYPOINT=/app/pkg/rds-sqlserver-db/entrypoint/entrypoint
